---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/keys/.*|
              (
                     ^package-lock.json$|
                     ^Pipfile|
                     ^pyproject.toml
              )
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.0.5
    hooks:
      - id: search-and-replace
        stages: [commit-msg, commit]
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.77.5
    hooks:
      - id: cfn-lint
        files: ^(.*/)?template\.(yml|yaml)$
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.3.239'
    hooks:
      - id: checkov
        args: ['--framework', 'cloudformation', '--quiet']
        files: ^(.*/)?template\.(yml|yaml)$
